version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: pharmacy-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pharmacy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: pharmacy-redis
    ports:
      - "6379:6379"

  nats:
    image: nats:2.10
    container_name: pharmacy-nats
    ports:
      - "4222:4222"
      - "8222:8222"

  product-service:
    build: .
    dns:
      - 1.1.1.1
      - 8.8.8.8
    container_name: product-service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      nats:
        condition: service_started
    environment:
      POSTGRES_DSN: postgres://user:pass@postgres:5432/pharmacy?sslmode=disable
      REDIS_ADDR: redis:6379
      NATS_URL: nats://nats:4222
      GRPC_PORT: :50051
    ports:
      - "50051:50051"

volumes:
  pgdata: